name: Build and Deploy to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Google Container Registry (GCR)
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.99f247dcecad7238b37a98d8a31054a79d0fff54 }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.jiomeet-vidyo }}/node-app:${{ github.sha }} .

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.jiomeet-vidyo }}/node-app:${{ github.sha }}
